<script src="https://giscus.app/client.js"
        data-repo="jimicat/jimicat.github.io"
        data-repo-id="R_kgDOM5EFCQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOM5EFCc4Cj2XL"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>